name: boh_humm
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # Cross-platform path manipulation library for Dart.
  path: ^1.9.0

  # Contains classes and methods for data persistence in SQLite.
  sqflite: ^2.3.3+1

  # Sends latest version of sqlite along with the app.
  sqlite3_flutter_libs: ^0.5.24
  
  # Navigation and dependency injection.
  flutter_modular: ^6.3.4
  
  # A dart package that helps implement the BLoC pattern.
  bloc: ^8.1.4

  # A Dart package that makes testing blocs and cubits easy.
  # Built to work with bloc and mocktail.
  bloc_test: ^9.1.7

  # Widgets that make it easy to integrate blocs and cubits into Flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  lints: ^3.0.0
  flutter_test:
    sdk: flutter

  # Allow the use of SQLite through the FFI interface in environments where SQLite is not natively available or 
  # where access to native APIs is required. Allows mocking sqflite during flutter regular unit testing.
  sqflite_common_ffi: ^2.3.3
  
  # Used to mock classes
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
